appname: "redis"
entrypoints:
  macvlan:
    cmd: "redis-server eru.conf"
  host:
    cmd: "redis-server eru.conf"
    network_mode: "host"
build:
  - "make"
  - "make install"
  - "mkdir -p /var/lib/redis"
  - "chmod 777 /var/lib/redis"
  - "cp *.conf /var/lib/redis"
  - "rm -rf ./*"
  - "mv /var/lib/redis/* ."
